### ISSUE TITLE
Extension "unixusers" not compliant: Missing function "extension_install_unixusers" in "/usr/share/ocsinventory-reports/ocsreports/extensions/unixusers/install.php"!

### ISSUE THREAD

**Issue by KpuCko** [bloodia/OCSInventory-NG-Plugin-unixusers#1]
Hello,
I'm trying to install this module. I've downloaded the whole repository and followed the guide, but when I go to extension manager I've got the message shown in the subject.

My version of iTOP is:

    PHP Version : 7.3.27
    Web Server : Apache/2.4.38 (Debian)
    Database Server : Debian 10 version 10.3.27-MariaDB-0+deb10u1
    Version OCSReports: 2.8.1

Do I missed something?
Thanks in advance.

**Comment by bloodia** [comment]
@KpuCko Hello,
It seems that the specifications of OCS Inventory have changed significantly. We recommend using the following official plugins.

[Unixusers](https://github.com/PluginsOCSInventory-NG/unixusers)

**Comment by KpuCko** [comment]
Great, thanks a lot @bloodia. You pointed me to the right direction.
Using the official module doesn't return any error.
Thanks again!
